variables:
  GIT_SUBMODULE_STRATEGY: normal

build_binaries:
  stage: build
  script:
    - autoreconf -si
    - './configure --with-matlab=$(dirname $(dirname $(readlink -f `which matlab`))) MATLAB_VERSION=$(echo version | matlab -nodesktop -nodisplay -nosplash 2>/dev/null | sed -En "/ans\ =/!d;n;n;s/^[^0-9]*([0-9]+\.[0-9]+).*$/\1/;p")'
    - make -j $(nproc) LN_S="cp -p"
  artifacts:
    paths:
      - matlab/preprocessor*/*
      - mex/octave/
      - mex/matlab/
      - dynare++/src/dynare++

build_doc:
  stage: build
  script:
    - autoreconf -si
    - ./configure --disable-matlab --disable-octave
    - make -j $(nproc) info pdf html
  artifacts:
    paths:
      - doc/dynare.info*
      - doc/dynare.html
      - doc/dynare.pdf
