variables:
  GIT_SUBMODULE_STRATEGY: normal
  TERM: linux

build_binaries:
  stage: build
  script:
    - autoreconf -si
    - './configure --with-matlab=$(dirname $(dirname $(readlink -f `which matlab`))) MATLAB_VERSION=$(echo version | matlab -nodesktop -nodisplay -nosplash 2>/dev/null | sed -En "/ans\ =/!d;n;n;s/^[^0-9]*([0-9]+\.[0-9]+).*$/\1/;p")'
    - make -j $(nproc) LN_S="cp -p"
  artifacts:
    paths:
      - matlab/preprocessor*/*
      - mex/octave/
      - mex/matlab/
      - dynare++/src/dynare++

build_doc:
  stage: build
  script:
    - autoreconf -si
    - ./configure --disable-matlab --disable-octave
    - make -j $(nproc) info pdf html
  artifacts:
    paths:
      - doc/dynare.info*
      - doc/dynare.html
      - doc/dynare.pdf

testsuite_matlab:
  stage: test
  script:
    - autoreconf -si
    - './configure --disable-octave --with-matlab=$(dirname $(dirname $(readlink -f `which matlab`))) MATLAB_VERSION=$(echo version | matlab -nodesktop -nodisplay -nosplash 2>/dev/null | sed -En "/ans\ =/!d;n;n;s/^[^0-9]*([0-9]+\.[0-9]+).*$/\1/;p")'
    - make -j $(($(nproc) / 2)) -C tests check-matlab
    - cat tests/run_test_matlab_output.txt
  artifacts:
    paths:
      - tests/*.m.log
      - tests/*.m.trs
      - tests/*/*.m.log
      - tests/*/*.m.trs
  dependencies:
    - build_binaries

testsuite_octave:
  stage: test
  variables:
    OPENBLAS_NUM_THREADS: 1
  script:
    - autoreconf -si
    - ./configure --disable-matlab
    - make -j $(nproc) -C tests check-octave
    - cat tests/run_test_octave_output.txt
  artifacts:
    paths:
      - tests/*.o.log
      - tests/*.o.trs
      - tests/*/*.o.log
      - tests/*/*.o.trs
  dependencies:
    - build_binaries
  only:
    - tags
    - schedules
    - web
